# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 240, 100, 80))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_beraber = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_beraber.setGeometry(QtCore.QRect(230, 360, 70, 40))
        self.pushButton_beraber.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_beraber.setObjectName("pushButton_beraber")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 240, 100, 80))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 160, 100, 80))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 160, 100, 80))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 160, 100, 80))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 80, 100, 80))
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 80, 100, 80))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 80, 100, 80))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 240, 100, 80))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 320, 100, 80))
        self.pushButton_0.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_toplama = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toplama.setGeometry(QtCore.QRect(230, 320, 70, 40))
        self.pushButton_toplama.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_toplama.setObjectName("pushButton_toplama")
        self.pushButton_cixma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cixma.setGeometry(QtCore.QRect(160, 320, 70, 40))
        self.pushButton_cixma.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_cixma.setObjectName("pushButton_cixma")
        self.pushButton_vurma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vurma.setGeometry(QtCore.QRect(160, 360, 70, 40))
        self.pushButton_vurma.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_vurma.setObjectName("pushButton_vurma")
        self.pushButton_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bolme.setGeometry(QtCore.QRect(100, 320, 60, 40))
        self.pushButton_bolme.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_bolme.setObjectName("pushButton_bolme")
        self.pushButton_faiz = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_faiz.setGeometry(QtCore.QRect(100, 360, 60, 40))
        self.pushButton_faiz.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_faiz.setObjectName("pushButton_faiz")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kalkulyator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_beraber.setText(_translate("MainWindow", "="))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_toplama.setText(_translate("MainWindow", "+"))
        self.pushButton_cixma.setText(_translate("MainWindow", "-"))
        self.pushButton_vurma.setText(_translate("MainWindow", "*"))
        self.pushButton_bolme.setText(_translate("MainWindow", "/"))
        self.pushButton_faiz.setText(_translate("MainWindow", "%"))

    def add_functions(self):
        self.pushButton_0.clicked.connect(lambda: self.write_number(self.pushButton_0.text()))
        self.pushButton_1.clicked.connect(lambda: self.write_number(self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(lambda: self.write_number(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write_number(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write_number(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda: self.write_number(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write_number(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write_number(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda: self.write_number(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda: self.write_number(self.pushButton_9.text()))
        self.pushButton_toplama.clicked.connect(lambda: self.write_number(self.pushButton_toplama.text()))
        self.pushButton_cixma.clicked.connect(lambda: self.write_number(self.pushButton_cixma.text()))
        self.pushButton_vurma.clicked.connect(lambda: self.write_number(self.pushButton_vurma.text()))
        self.pushButton_bolme.clicked.connect(lambda: self.write_number(self.pushButton_bolme.text()))

        self.pushButton_beraber.clicked.connect(self.results)

    def write_number(self, number):
        if self.label.text() == "0" or self.is_equal:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text()+number)

    def results(self):
        if not self.is_equal:
            res = eval(self.label.text())
            self.label.setText('Cavab: ' + str(res))
            self.is_equal = True
        else:
            error = QMessageBox()
            error.setWindowTitle('Error')
            error.setText('Indi bu emeliyyat yerine yetirmek mumkun deyil')
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok | QMessageBox.Reset)

            error.setDefaultButton(QMessageBox.Ok)
            error.setInformativeText('Iki defe bu emeliyyati yerine yetirmek olmaz')
            error.setDetailedText("Detalar")

            error.buttonClicked.connect(self.popup_action)

            error.exec_()


    def popup_action(self, btn):
        if btn.text() == 'Ok':
            print('Ok')
        elif btn.text() == 'Reset':
            self.label.setText('')
            self.is_equal = False



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
